# Site settings
title: M5 Digitale Fraude (づ｡◕‿‿◕｡)づ
description: "DIT IS EEN TESTJE NEGEER DEZE SITE DOEI"
url: "m5test.vanmonsjou.xyz"
author:
  name: "Daan van Monsjou"
  email: "daan@vanmonsjou.xyz"
  url: "http://www.jacoporabolini.com"

# Build settings
baseurl: /emerald # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
