# Site settings
title: (づ｡◕‿‿◕｡)づ ~ M5 ~
description: "DIT IS EEN TESTJE NEGEER DEZE SITE DOEI"
url: "https://m5test.vanmonsjou.xyz"
author:
  name: "Daan van Monsjou"
  email: "daan@vanmonsjou.xyz"
  url: "https://m5test.vanmonsjou.xyz"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: true

theme: jekyll-theme-cayman
